#!/bin/bash
#$ -cwd
#$ -v PATH,LD_LIBRARY_PATH,CLASSPATH
#$ -l m_mem_free=10G
#$ -l tmp_free=50G

Human=/data/abdelwao-lab/hoggs/Reference_genomes/hg19/gencode.v19.annotation.gtf
Mouse=/data/abdelwao-lab/hoggs/Reference_genomes/GRCm38/gencode.vM25.primary_assembly.annotation.gtf
Out=./RNASeq_counts_gene_id.txt
Bams=./*.sorted.bam

featureCounts -p -T 20 -O -F GTF -t exon -g gene_name -a $Human -o $Out $Bams
