#!/bin/bash
#$ -cwd
#$ -v PATH,LD_LIBRARY_PATH,CLASSPATH
#$ -l m_mem_free=10G
#$ -l tmp_free=50G
for i in *S2[23]*R1_001_val_1.fq.gz
do
        echo $i
        R2=${i/R1_001_val_1/R2_001_val_2}
        echo $R2
        name=${i/R1_001_val_1.fq.gz/}
        echo $name
        STAR --genomeDir /grid/mills/home/xsun/index_file/RNA_STAR/hg38_STAR --runThreadN 8 --readFilesIn $i $R2 --twopassMode Basic --twopass1readsN -1 --sjdbOverhang 100 --readFilesCommand zcat --outFileNamePrefix $name

done
