#!/bin/bash
#$ -cwd
#$ -v PATH,LD_LIBRARY_PATH,CLASSPATH
#$ -l m_mem_free=10G
#$ -l tmp_free=50G
for i in *R1*val_1.fq.gz
do
        echo $i
        R2=${i/R1_val_1/R2_val_2}
        echo $R2
        name=${i/R1_val_1.fq.gz/}
        echo $name
        STAR --genomeDir /grid/mills/home/xsun/index_file/RNA_STAR/mm10_STAR --runThreadN 8 --readFilesIn $i $R2 --twopassMode Basic --twopass1readsN -1 --sjdbOverhang 100 --readFilesCommand zcat --outFileNamePrefix $name
        samtools view -@ 8 -Sb ${name}Aligned.out.sam  > ${name}Aligned.out.bam
        samtools sort ${name}Aligned.out.bam > ${name}Aligned.out.sorted.bam
        rm ${name}Aligned.out.bam
        samtools rmdup ${name}Aligned.out.sorted.bam ${name}Aligned.out.sorted.rd.bam
        samtools index ${name}Aligned.out.sorted.rd.bam
        rm ${name}Aligned.out.sorted.bam
done
